### ISSUE TITLE
Landlock crate update

### ISSUE THREAD

**Issue by l0kod** [micheleberetta98/rust-wasm-landlock#1]
Hi,

I created a new release for the Landlock crate: https://github.com/landlock-lsm/rust-landlock/pull/32
It would be better to use this 0.2.0 version instead of the main branch that could soon break the API.

**Comment by micheleberetta98** [comment]
Hi, thank you for the heads up.
I'll update the version as soon as I can.

**Comment by micheleberetta98** [comment]
Updated landlock to version 0.2.0 as of today.
